// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Hardware backing a key, reported as achieved and never assumed from the
/// request. Crosses the channel as a pinned token, not an ordinal.
enum SecurityLevelWire: Int, CaseIterable {
  case secureEnclave = 0
  case strongBox = 1
  case tee = 2
  case tpm = 3
  case software = 4
}

/// How the achieved level was determined. Only `attested` is cryptographic
/// proof; every other value is an on-device self-report.
enum TierEvidenceWire: Int, CaseIterable {
  case attested = 0
  case keyInfoReadback = 1
  case seTokenPresent = 2
  case inferred = 3
  case selfReportUnverified = 4
}

/// The tier-selection policy kind. `atLeast` carries its class in [KeySpecWire].
enum TierPolicyKindWire: Int, CaseIterable {
  case strongest = 0
  case atLeast = 1
  case bestEffort = 2
}

/// A class in the tier partial order; `discreteSecure` outranks
/// `trustedEnvironment`.
enum HardwareClassWire: Int, CaseIterable {
  case discreteSecure = 0
  case trustedEnvironment = 1
}

/// The presence check bound to a created key, reported in a tier report.
enum AuthClassWire: Int, CaseIterable {
  case none = 0
  case biometricOnly = 1
  case biometricOrDeviceCredential = 2
  case deviceCredentialOnly = 3
}

/// Public-key wire format: uncompressed X9.63 point or DER SubjectPublicKeyInfo.
enum PublicKeyFormatWire: Int, CaseIterable {
  case rawX962 = 0
  case spki = 1
}

/// Attestation wire format: a certificate chain or none.
enum AttestationFormatWire: Int, CaseIterable {
  case androidKeyChain = 0
  case none = 1
}

/// Signature wire encoding: X9.62 DER or fixed 64-byte r||s.
enum SignEncodingWire: Int, CaseIterable {
  case der = 0
  case rawRS = 1
}

/// A key-generation request. Keys created through this surface carry no presence
/// check; the achieved tier is read back from the created key, never assumed.
///
/// Generated class from Pigeon that represents data sent in messages.
struct KeySpecWire: Hashable, CustomStringConvertible {
  /// Stable, app-scoped name for the key.
  var alias: String
  /// Tier selection kind.
  var tierPolicyKind: TierPolicyKindWire
  /// Set only when [tierPolicyKind] is `atLeast`; null otherwise.
  var atLeastClass: HardwareClassWire? = nil
  /// Bound into the key at generation; there is no call-time challenge.
  var attestationChallenge: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KeySpecWire? {
    let alias = pigeonVar_list[0] as! String
    let tierPolicyKind = pigeonVar_list[1] as! TierPolicyKindWire
    let atLeastClass: HardwareClassWire? = nilOrValue(pigeonVar_list[2])
    let attestationChallenge: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[3])

    return KeySpecWire(
      alias: alias,
      tierPolicyKind: tierPolicyKind,
      atLeastClass: atLeastClass,
      attestationChallenge: attestationChallenge
    )
  }
  func toList() -> [Any?] {
    return [
      alias,
      tierPolicyKind,
      atLeastClass,
      attestationChallenge,
    ]
  }
  static func == (lhs: KeySpecWire, rhs: KeySpecWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.alias, rhs.alias) && MessagesPigeonInternal.deepEquals(lhs.tierPolicyKind, rhs.tierPolicyKind) && MessagesPigeonInternal.deepEquals(lhs.atLeastClass, rhs.atLeastClass) && MessagesPigeonInternal.deepEquals(lhs.attestationChallenge, rhs.attestationChallenge)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KeySpecWire")
    MessagesPigeonInternal.deepHash(value: alias, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: tierPolicyKind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: atLeastClass, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: attestationChallenge, hasher: &hasher)
  }

  public var description: String {
    return "KeySpecWire(alias: \(String(describing: alias)), tierPolicyKind: \(String(describing: tierPolicyKind)), atLeastClass: \(String(describing: atLeastClass)), attestationChallenge: \(String(describing: attestationChallenge)))"
  }
}

/// One report shape for every operation that reads a key's tier. `requested` and
/// `authEnforced` are null on a re-read, where the policy is not stored with the
/// key and the platform may not read the created access control back.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SecurityTierReportWire: Hashable, CustomStringConvertible {
  var achieved: SecurityLevelWire
  var requestedKind: TierPolicyKindWire? = nil
  var requestedAtLeastClass: HardwareClassWire? = nil
  var meetsFloor: Bool
  var evidence: TierEvidenceWire
  var authEnforced: AuthClassWire? = nil
  var invalidated: Bool
  var schemaVersion: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SecurityTierReportWire? {
    let achieved = pigeonVar_list[0] as! SecurityLevelWire
    let requestedKind: TierPolicyKindWire? = nilOrValue(pigeonVar_list[1])
    let requestedAtLeastClass: HardwareClassWire? = nilOrValue(pigeonVar_list[2])
    let meetsFloor = pigeonVar_list[3] as! Bool
    let evidence = pigeonVar_list[4] as! TierEvidenceWire
    let authEnforced: AuthClassWire? = nilOrValue(pigeonVar_list[5])
    let invalidated = pigeonVar_list[6] as! Bool
    let schemaVersion = pigeonVar_list[7] as! Int64

    return SecurityTierReportWire(
      achieved: achieved,
      requestedKind: requestedKind,
      requestedAtLeastClass: requestedAtLeastClass,
      meetsFloor: meetsFloor,
      evidence: evidence,
      authEnforced: authEnforced,
      invalidated: invalidated,
      schemaVersion: schemaVersion
    )
  }
  func toList() -> [Any?] {
    return [
      achieved,
      requestedKind,
      requestedAtLeastClass,
      meetsFloor,
      evidence,
      authEnforced,
      invalidated,
      schemaVersion,
    ]
  }
  static func == (lhs: SecurityTierReportWire, rhs: SecurityTierReportWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.achieved, rhs.achieved) && MessagesPigeonInternal.deepEquals(lhs.requestedKind, rhs.requestedKind) && MessagesPigeonInternal.deepEquals(lhs.requestedAtLeastClass, rhs.requestedAtLeastClass) && MessagesPigeonInternal.deepEquals(lhs.meetsFloor, rhs.meetsFloor) && MessagesPigeonInternal.deepEquals(lhs.evidence, rhs.evidence) && MessagesPigeonInternal.deepEquals(lhs.authEnforced, rhs.authEnforced) && MessagesPigeonInternal.deepEquals(lhs.invalidated, rhs.invalidated) && MessagesPigeonInternal.deepEquals(lhs.schemaVersion, rhs.schemaVersion)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SecurityTierReportWire")
    MessagesPigeonInternal.deepHash(value: achieved, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: requestedKind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: requestedAtLeastClass, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: meetsFloor, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: evidence, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: authEnforced, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: invalidated, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: schemaVersion, hasher: &hasher)
  }

  public var description: String {
    return "SecurityTierReportWire(achieved: \(String(describing: achieved)), requestedKind: \(String(describing: requestedKind)), requestedAtLeastClass: \(String(describing: requestedAtLeastClass)), meetsFloor: \(String(describing: meetsFloor)), evidence: \(String(describing: evidence)), authEnforced: \(String(describing: authEnforced)), invalidated: \(String(describing: invalidated)), schemaVersion: \(String(describing: schemaVersion)))"
  }
}

/// Options for a signature.
///
/// Generated class from Pigeon that represents data sent in messages.
struct SignOptionsWire: Hashable, CustomStringConvertible {
  var encoding: SignEncodingWire


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SignOptionsWire? {
    let encoding = pigeonVar_list[0] as! SignEncodingWire

    return SignOptionsWire(
      encoding: encoding
    )
  }
  func toList() -> [Any?] {
    return [
      encoding
    ]
  }
  static func == (lhs: SignOptionsWire, rhs: SignOptionsWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.encoding, rhs.encoding)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SignOptionsWire")
    MessagesPigeonInternal.deepHash(value: encoding, hasher: &hasher)
  }

  public var description: String {
    return "SignOptionsWire(encoding: \(String(describing: encoding)))"
  }
}

/// The attestation for a key: a certificate chain (`androidKeyChain`), one
/// DER-encoded certificate per element, or `none` with a null chain. The library
/// produces attestation and never verifies it.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AttestationResultWire: Hashable, CustomStringConvertible {
  var format: AttestationFormatWire
  var chain: [FlutterStandardTypedData?]? = nil
  var schemaVersion: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AttestationResultWire? {
    let format = pigeonVar_list[0] as! AttestationFormatWire
    let chain: [FlutterStandardTypedData?]? = nilOrValue(pigeonVar_list[1])
    let schemaVersion = pigeonVar_list[2] as! Int64

    return AttestationResultWire(
      format: format,
      chain: chain,
      schemaVersion: schemaVersion
    )
  }
  func toList() -> [Any?] {
    return [
      format,
      chain,
      schemaVersion,
    ]
  }
  static func == (lhs: AttestationResultWire, rhs: AttestationResultWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.format, rhs.format) && MessagesPigeonInternal.deepEquals(lhs.chain, rhs.chain) && MessagesPigeonInternal.deepEquals(lhs.schemaVersion, rhs.schemaVersion)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AttestationResultWire")
    MessagesPigeonInternal.deepHash(value: format, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: chain, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: schemaVersion, hasher: &hasher)
  }

  public var description: String {
    return "AttestationResultWire(format: \(String(describing: format)), chain: \(String(describing: chain)), schemaVersion: \(String(describing: schemaVersion)))"
  }
}

/// The result of generating a key: an opaque handle id carrying no key material,
/// and the tier report read back from the created key.
///
/// Generated class from Pigeon that represents data sent in messages.
struct GenerateResultWire: Hashable, CustomStringConvertible {
  var handleId: String
  var report: SecurityTierReportWire


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenerateResultWire? {
    let handleId = pigeonVar_list[0] as! String
    let report = pigeonVar_list[1] as! SecurityTierReportWire

    return GenerateResultWire(
      handleId: handleId,
      report: report
    )
  }
  func toList() -> [Any?] {
    return [
      handleId,
      report,
    ]
  }
  static func == (lhs: GenerateResultWire, rhs: GenerateResultWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.handleId, rhs.handleId) && MessagesPigeonInternal.deepEquals(lhs.report, rhs.report)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GenerateResultWire")
    MessagesPigeonInternal.deepHash(value: handleId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: report, hasher: &hasher)
  }

  public var description: String {
    return "GenerateResultWire(handleId: \(String(describing: handleId)), report: \(String(describing: report)))"
  }
}

/// A public key in one of the pinned formats. There is no matching private-key
/// surface anywhere in the contract.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PublicKeyWire: Hashable, CustomStringConvertible {
  var format: PublicKeyFormatWire
  var bytes: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PublicKeyWire? {
    let format = pigeonVar_list[0] as! PublicKeyFormatWire
    let bytes = pigeonVar_list[1] as! FlutterStandardTypedData

    return PublicKeyWire(
      format: format,
      bytes: bytes
    )
  }
  func toList() -> [Any?] {
    return [
      format,
      bytes,
    ]
  }
  static func == (lhs: PublicKeyWire, rhs: PublicKeyWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.format, rhs.format) && MessagesPigeonInternal.deepEquals(lhs.bytes, rhs.bytes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PublicKeyWire")
    MessagesPigeonInternal.deepHash(value: format, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bytes, hasher: &hasher)
  }

  public var description: String {
    return "PublicKeyWire(format: \(String(describing: format)), bytes: \(String(describing: bytes)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SecurityLevelWire(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TierEvidenceWire(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TierPolicyKindWire(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HardwareClassWire(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AuthClassWire(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PublicKeyFormatWire(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AttestationFormatWire(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SignEncodingWire(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      return KeySpecWire.fromList(self.readValue() as! [Any?])
    case 138:
      return SecurityTierReportWire.fromList(self.readValue() as! [Any?])
    case 139:
      return SignOptionsWire.fromList(self.readValue() as! [Any?])
    case 140:
      return AttestationResultWire.fromList(self.readValue() as! [Any?])
    case 141:
      return GenerateResultWire.fromList(self.readValue() as! [Any?])
    case 142:
      return PublicKeyWire.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SecurityLevelWire {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? TierEvidenceWire {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? TierPolicyKindWire {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? HardwareClassWire {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? AuthClassWire {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? PublicKeyFormatWire {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? AttestationFormatWire {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? SignEncodingWire {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? KeySpecWire {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? SecurityTierReportWire {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? SignOptionsWire {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? AttestationResultWire {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? GenerateResultWire {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? PublicKeyWire {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// The calls Dart makes into the native core. Errors do not cross as data: the
/// core throws a platform error whose code is one of the closed error tokens in
/// `conformance/errors.json`, which the idiomatic layer maps to a typed
/// exception. The native side is not more trusted than Dart; both run in the
/// same process and the only trust anchors are the hardware and a remote
/// attestation verifier this library never calls.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SignetHostApi {
  /// Generates a non-exportable P-256 key. Fails `keyAlreadyExists` on an
  /// existing alias, `unavailableTier` when a hard policy cannot be met.
  func generateKey(spec: KeySpecWire) throws -> GenerateResultWire
  /// Public key only; the private key has no export path.
  func getPublicKey(handleId: String, format: PublicKeyFormatWire) throws -> PublicKeyWire
  /// Signs a 32-byte digest with no authentication prompt. A wrong-length digest
  /// is rejected `invalidArgument` before any key access.
  func sign(handleId: String, digest: FlutterStandardTypedData, options: SignOptionsWire, completion: @escaping (Result<FlutterStandardTypedData, Error>) -> Void)
  /// Attestation bound at generation; takes no call-time challenge.
  func getAttestation(handleId: String) throws -> AttestationResultWire
  /// Re-reads a key's tier; does not throw on an invalidated-but-present key.
  func getSecurityTier(handleId: String) throws -> SecurityTierReportWire
  /// Whether a key exists for the alias.
  func exists(alias: String) throws -> Bool
  /// Deletes the key for the alias. Idempotent: a missing alias is not an error.
  func deleteKey(alias: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SignetHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `SignetHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SignetHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Generates a non-exportable P-256 key. Fails `keyAlreadyExists` on an
    /// existing alias, `unavailableTier` when a hard policy cannot be met.
    let generateKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.signet.SignetHostApi.generateKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let specArg = args[0] as! KeySpecWire
        do {
          let result = try api.generateKey(spec: specArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      generateKeyChannel.setMessageHandler(nil)
    }
    /// Public key only; the private key has no export path.
    let getPublicKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.signet.SignetHostApi.getPublicKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPublicKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleIdArg = args[0] as! String
        let formatArg = args[1] as! PublicKeyFormatWire
        do {
          let result = try api.getPublicKey(handleId: handleIdArg, format: formatArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPublicKeyChannel.setMessageHandler(nil)
    }
    /// Signs a 32-byte digest with no authentication prompt. A wrong-length digest
    /// is rejected `invalidArgument` before any key access.
    let signChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.signet.SignetHostApi.sign\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleIdArg = args[0] as! String
        let digestArg = args[1] as! FlutterStandardTypedData
        let optionsArg = args[2] as! SignOptionsWire
        api.sign(handleId: handleIdArg, digest: digestArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      signChannel.setMessageHandler(nil)
    }
    /// Attestation bound at generation; takes no call-time challenge.
    let getAttestationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.signet.SignetHostApi.getAttestation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAttestationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleIdArg = args[0] as! String
        do {
          let result = try api.getAttestation(handleId: handleIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAttestationChannel.setMessageHandler(nil)
    }
    /// Re-reads a key's tier; does not throw on an invalidated-but-present key.
    let getSecurityTierChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.signet.SignetHostApi.getSecurityTier\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSecurityTierChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleIdArg = args[0] as! String
        do {
          let result = try api.getSecurityTier(handleId: handleIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getSecurityTierChannel.setMessageHandler(nil)
    }
    /// Whether a key exists for the alias.
    let existsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.signet.SignetHostApi.exists\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      existsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let aliasArg = args[0] as! String
        do {
          let result = try api.exists(alias: aliasArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      existsChannel.setMessageHandler(nil)
    }
    /// Deletes the key for the alias. Idempotent: a missing alias is not an error.
    let deleteKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.signet.SignetHostApi.deleteKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let aliasArg = args[0] as! String
        do {
          try api.deleteKey(alias: aliasArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deleteKeyChannel.setMessageHandler(nil)
    }
  }
}
