// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Nirapod Labs
// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Hardware backing a key, reported as achieved and never assumed from the
/// request. Generated per build and crosses the channel as its declared ordinal,
/// so append new members and never reorder.
enum SecurityLevelWire {
  secureEnclave,
  strongBox,
  tee,
}

/// How the achieved level was determined.
enum TierEvidenceWire {
  keyInfoReadback,
  seTokenPresent,
}

/// The tier-selection policy kind. `atLeast` carries its class in [KeySpecWire].
enum TierPolicyKindWire {
  strongest,
  atLeast,
}

/// A class in the tier partial order; `discreteSecure` outranks
/// `trustedEnvironment`.
enum HardwareClassWire {
  discreteSecure,
  trustedEnvironment,
}

/// The presence check REQUESTED for a key at generation. Three values; `none`
/// is a silent key. Distinct from [AuthClassWire], the four-value class read
/// back from the created key and reported in a tier report.
enum AuthRequirementWire {
  none,
  biometricOnly,
  biometricOrDeviceCredential,
}

/// The presence check bound to a created key, reported in a tier report.
enum AuthClassWire {
  none,
  biometricOnly,
  biometricOrDeviceCredential,
  deviceCredentialOnly,
}

/// Public-key wire format: uncompressed X9.63 point or DER SubjectPublicKeyInfo.
enum PublicKeyFormatWire {
  rawX962,
  spki,
}

/// Attestation wire format: a certificate chain or none.
enum AttestationFormatWire {
  androidKeyChain,
  none,
}

/// Signature wire encoding: X9.62 DER or fixed 64-byte r||s.
enum SignEncodingWire {
  der,
  rawRS,
}

/// A key-generation request. The achieved tier and auth class are read back from
/// the created key, never assumed from the request.
class KeySpecWire {
  KeySpecWire({
    required this.alias,
    required this.tierPolicyKind,
    this.atLeastClass,
    required this.authRequirement,
    this.authValiditySeconds,
    required this.invalidateOnBiometricEnrollment,
    this.attestationChallenge,
  });

  /// Stable, app-scoped name for the key.
  String alias;

  /// Tier selection kind.
  TierPolicyKindWire tierPolicyKind;

  /// Set only when [tierPolicyKind] is `atLeast`; null otherwise.
  HardwareClassWire? atLeastClass;

  /// The presence check to bind to the key; `none` creates a silent key.
  AuthRequirementWire authRequirement;

  /// Auth reuse window in seconds; null and 0 both mean per-use. Baked into the
  /// key where the platform supports it (Android); a sign-time value elsewhere.
  int? authValiditySeconds;

  /// Whether a biometric re-enrollment invalidates the key.
  bool invalidateOnBiometricEnrollment;

  /// Bound into the key at generation; there is no call-time challenge.
  Uint8List? attestationChallenge;

  List<Object?> _toList() {
    return <Object?>[
      alias,
      tierPolicyKind,
      atLeastClass,
      authRequirement,
      authValiditySeconds,
      invalidateOnBiometricEnrollment,
      attestationChallenge,
    ];
  }

  Object encode() {
    return _toList();  }

  static KeySpecWire decode(Object result) {
    result as List<Object?>;
    return KeySpecWire(
      alias: result[0]! as String,
      tierPolicyKind: result[1]! as TierPolicyKindWire,
      atLeastClass: result[2] as HardwareClassWire?,
      authRequirement: result[3]! as AuthRequirementWire,
      authValiditySeconds: result[4] as int?,
      invalidateOnBiometricEnrollment: result[5]! as bool,
      attestationChallenge: result[6] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KeySpecWire || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(alias, other.alias) && _deepEquals(tierPolicyKind, other.tierPolicyKind) && _deepEquals(atLeastClass, other.atLeastClass) && _deepEquals(authRequirement, other.authRequirement) && _deepEquals(authValiditySeconds, other.authValiditySeconds) && _deepEquals(invalidateOnBiometricEnrollment, other.invalidateOnBiometricEnrollment) && _deepEquals(attestationChallenge, other.attestationChallenge);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeySpecWire(alias: $alias, tierPolicyKind: $tierPolicyKind, atLeastClass: $atLeastClass, authRequirement: $authRequirement, authValiditySeconds: $authValiditySeconds, invalidateOnBiometricEnrollment: $invalidateOnBiometricEnrollment, attestationChallenge: $attestationChallenge)';
  }
}

/// One report shape for every operation that reads a key's tier. `requested` and
/// `authEnforced` are null on a re-read, where the policy is not stored with the
/// key and the platform may not read the created access control back.
class SecurityTierReportWire {
  SecurityTierReportWire({
    required this.achieved,
    this.requestedKind,
    this.requestedAtLeastClass,
    required this.evidence,
    this.authEnforced,
    required this.invalidated,
    required this.schemaVersion,
  });

  SecurityLevelWire achieved;

  TierPolicyKindWire? requestedKind;

  HardwareClassWire? requestedAtLeastClass;

  TierEvidenceWire evidence;

  AuthClassWire? authEnforced;

  bool invalidated;

  int schemaVersion;

  List<Object?> _toList() {
    return <Object?>[
      achieved,
      requestedKind,
      requestedAtLeastClass,
      evidence,
      authEnforced,
      invalidated,
      schemaVersion,
    ];
  }

  Object encode() {
    return _toList();  }

  static SecurityTierReportWire decode(Object result) {
    result as List<Object?>;
    return SecurityTierReportWire(
      achieved: result[0]! as SecurityLevelWire,
      requestedKind: result[1] as TierPolicyKindWire?,
      requestedAtLeastClass: result[2] as HardwareClassWire?,
      evidence: result[3]! as TierEvidenceWire,
      authEnforced: result[4] as AuthClassWire?,
      invalidated: result[5]! as bool,
      schemaVersion: result[6]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SecurityTierReportWire || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(achieved, other.achieved) && _deepEquals(requestedKind, other.requestedKind) && _deepEquals(requestedAtLeastClass, other.requestedAtLeastClass) && _deepEquals(evidence, other.evidence) && _deepEquals(authEnforced, other.authEnforced) && _deepEquals(invalidated, other.invalidated) && _deepEquals(schemaVersion, other.schemaVersion);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SecurityTierReportWire(achieved: $achieved, requestedKind: $requestedKind, requestedAtLeastClass: $requestedAtLeastClass, evidence: $evidence, authEnforced: $authEnforced, invalidated: $invalidated, schemaVersion: $schemaVersion)';
  }
}

/// Options for a signature.
class SignOptionsWire {
  SignOptionsWire({
    required this.encoding,
  });

  SignEncodingWire encoding;

  List<Object?> _toList() {
    return <Object?>[
      encoding,
    ];
  }

  Object encode() {
    return _toList();  }

  static SignOptionsWire decode(Object result) {
    result as List<Object?>;
    return SignOptionsWire(
      encoding: result[0]! as SignEncodingWire,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SignOptionsWire || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encoding, other.encoding);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SignOptionsWire(encoding: $encoding)';
  }
}

/// The attestation for a key: a certificate chain (`androidKeyChain`), one
/// DER-encoded certificate per element, or `none` with a null chain. The library
/// produces attestation and never verifies it.
class AttestationResultWire {
  AttestationResultWire({
    required this.format,
    this.chain,
    required this.schemaVersion,
  });

  AttestationFormatWire format;

  List<Uint8List?>? chain;

  int schemaVersion;

  List<Object?> _toList() {
    return <Object?>[
      format,
      chain,
      schemaVersion,
    ];
  }

  Object encode() {
    return _toList();  }

  static AttestationResultWire decode(Object result) {
    result as List<Object?>;
    return AttestationResultWire(
      format: result[0]! as AttestationFormatWire,
      chain: (result[1] as List<Object?>?)?.cast<Uint8List?>(),
      schemaVersion: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AttestationResultWire || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(format, other.format) && _deepEquals(chain, other.chain) && _deepEquals(schemaVersion, other.schemaVersion);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AttestationResultWire(format: $format, chain: $chain, schemaVersion: $schemaVersion)';
  }
}

/// The result of generating a key: an opaque handle id carrying no key material,
/// and the tier report read back from the created key.
class GenerateResultWire {
  GenerateResultWire({
    required this.handleId,
    required this.report,
  });

  String handleId;

  SecurityTierReportWire report;

  List<Object?> _toList() {
    return <Object?>[
      handleId,
      report,
    ];
  }

  Object encode() {
    return _toList();  }

  static GenerateResultWire decode(Object result) {
    result as List<Object?>;
    return GenerateResultWire(
      handleId: result[0]! as String,
      report: result[1]! as SecurityTierReportWire,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GenerateResultWire || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(handleId, other.handleId) && _deepEquals(report, other.report);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'GenerateResultWire(handleId: $handleId, report: $report)';
  }
}

/// A public key in one of the pinned formats. There is no matching private-key
/// surface anywhere in the contract.
class PublicKeyWire {
  PublicKeyWire({
    required this.format,
    required this.bytes,
  });

  PublicKeyFormatWire format;

  Uint8List bytes;

  List<Object?> _toList() {
    return <Object?>[
      format,
      bytes,
    ];
  }

  Object encode() {
    return _toList();  }

  static PublicKeyWire decode(Object result) {
    result as List<Object?>;
    return PublicKeyWire(
      format: result[0]! as PublicKeyFormatWire,
      bytes: result[1]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PublicKeyWire || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(format, other.format) && _deepEquals(bytes, other.bytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PublicKeyWire(format: $format, bytes: $bytes)';
  }
}

/// The prompt for an auth-gated sign, non-null on [SignetHostApi.sign] only for a
/// gated key. The native side presents it and authenticates the hardware key
/// directly; a Dart-shown prompt could not. [authRequirement] must match the
/// key's and selects the prompt's authenticators.
class AuthPromptWire {
  AuthPromptWire({
    required this.title,
    this.subtitle,
    required this.negativeButtonText,
    required this.authRequirement,
  });

  String title;

  String? subtitle;

  /// The fallback button label on a biometric-only prompt.
  String negativeButtonText;

  /// Selects the prompt's authenticators; matches the key's requirement.
  AuthRequirementWire authRequirement;

  List<Object?> _toList() {
    return <Object?>[
      title,
      subtitle,
      negativeButtonText,
      authRequirement,
    ];
  }

  Object encode() {
    return _toList();  }

  static AuthPromptWire decode(Object result) {
    result as List<Object?>;
    return AuthPromptWire(
      title: result[0]! as String,
      subtitle: result[1] as String?,
      negativeButtonText: result[2]! as String,
      authRequirement: result[3]! as AuthRequirementWire,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AuthPromptWire || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(title, other.title) && _deepEquals(subtitle, other.subtitle) && _deepEquals(negativeButtonText, other.negativeButtonText) && _deepEquals(authRequirement, other.authRequirement);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AuthPromptWire(title: $title, subtitle: $subtitle, negativeButtonText: $negativeButtonText, authRequirement: $authRequirement)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is SecurityLevelWire) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is TierEvidenceWire) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is TierPolicyKindWire) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is HardwareClassWire) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is AuthRequirementWire) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is AuthClassWire) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is PublicKeyFormatWire) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is AttestationFormatWire) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    }    else if (value is SignEncodingWire) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    }    else if (value is KeySpecWire) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is SecurityTierReportWire) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is SignOptionsWire) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is AttestationResultWire) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is GenerateResultWire) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is PublicKeyWire) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is AuthPromptWire) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : SecurityLevelWire.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : TierEvidenceWire.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : TierPolicyKindWire.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : HardwareClassWire.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : AuthRequirementWire.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : AuthClassWire.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : PublicKeyFormatWire.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : AttestationFormatWire.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null ? null : SignEncodingWire.values[value];
      case 138:
        return KeySpecWire.decode(readValue(buffer)!);
      case 139:
        return SecurityTierReportWire.decode(readValue(buffer)!);
      case 140:
        return SignOptionsWire.decode(readValue(buffer)!);
      case 141:
        return AttestationResultWire.decode(readValue(buffer)!);
      case 142:
        return GenerateResultWire.decode(readValue(buffer)!);
      case 143:
        return PublicKeyWire.decode(readValue(buffer)!);
      case 144:
        return AuthPromptWire.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// The calls Dart makes into the native core. Errors do not cross as data: the
/// core throws a platform error whose code is one of the closed error tokens in
/// `conformance/errors.json`, which the idiomatic layer maps to a typed
/// exception. The native side is not more trusted than Dart; both run in the
/// same process and the only trust anchors are the hardware and a remote
/// attestation verifier this library never calls.
class SignetHostApi {
  /// Constructor for [SignetHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SignetHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Generates a non-exportable P-256 key. Fails `keyAlreadyExists` on an
  /// existing alias, `unavailableTier` when a hard policy cannot be met.
  Future<GenerateResultWire> generateKey(KeySpecWire spec) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.signet.SignetHostApi.generateKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[spec]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as GenerateResultWire;
  }

  /// Public key only; the private key has no export path.
  Future<PublicKeyWire> getPublicKey(String handleId, PublicKeyFormatWire format) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.signet.SignetHostApi.getPublicKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[handleId, format]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PublicKeyWire;
  }

  /// Signs a 32-byte digest. A null [prompt] is the silent path and raises no
  /// prompt; a non-null [prompt] drives an auth-gated sign whose biometric prompt
  /// the native side presents and authenticates directly. A wrong-length digest
  /// is rejected `invalidArgument` before any key access. A second concurrent
  /// gated sign is rejected `authInProgress`; a gated key with no presentable host
  /// UI raises `authContextRequired`.
  Future<Uint8List> sign(String handleId, Uint8List digest, SignOptionsWire options, AuthPromptWire? prompt) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.signet.SignetHostApi.sign$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[handleId, digest, options, prompt]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }

  /// Attestation bound at generation; takes no call-time challenge.
  Future<AttestationResultWire> getAttestation(String handleId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.signet.SignetHostApi.getAttestation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[handleId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AttestationResultWire;
  }

  /// Re-reads a key's tier; does not throw on an invalidated-but-present key.
  Future<SecurityTierReportWire> getSecurityTier(String handleId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.signet.SignetHostApi.getSecurityTier$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[handleId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as SecurityTierReportWire;
  }

  /// Whether a key exists for the alias.
  Future<bool> exists(String alias) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.signet.SignetHostApi.exists$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[alias]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Deletes the key for the alias. Idempotent: a missing alias is not an error.
  Future<void> deleteKey(String alias) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.signet.SignetHostApi.deleteKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[alias]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
