// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Nirapod Labs
// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package org.nirapod.signet

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Hardware backing a key, reported as achieved and never assumed from the
 * request. Crosses the channel as a pinned token, not an ordinal.
 */
enum class SecurityLevelWire(val raw: Int) {
  SECURE_ENCLAVE(0),
  STRONG_BOX(1),
  TEE(2),
  TPM(3),
  SOFTWARE(4);

  companion object {
    fun ofRaw(raw: Int): SecurityLevelWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * How the achieved level was determined. Only `attested` is cryptographic
 * proof; every other value is an on-device self-report.
 */
enum class TierEvidenceWire(val raw: Int) {
  ATTESTED(0),
  KEY_INFO_READBACK(1),
  SE_TOKEN_PRESENT(2),
  INFERRED(3),
  SELF_REPORT_UNVERIFIED(4);

  companion object {
    fun ofRaw(raw: Int): TierEvidenceWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The tier-selection policy kind. `atLeast` carries its class in [KeySpecWire]. */
enum class TierPolicyKindWire(val raw: Int) {
  STRONGEST(0),
  AT_LEAST(1),
  BEST_EFFORT(2);

  companion object {
    fun ofRaw(raw: Int): TierPolicyKindWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A class in the tier partial order; `discreteSecure` outranks
 * `trustedEnvironment`.
 */
enum class HardwareClassWire(val raw: Int) {
  DISCRETE_SECURE(0),
  TRUSTED_ENVIRONMENT(1);

  companion object {
    fun ofRaw(raw: Int): HardwareClassWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * The presence check REQUESTED for a key at generation. Three values; `none`
 * is a silent key. Distinct from [AuthClassWire], the four-value class read
 * back from the created key and reported in a tier report.
 */
enum class AuthRequirementWire(val raw: Int) {
  NONE(0),
  BIOMETRIC_ONLY(1),
  BIOMETRIC_OR_DEVICE_CREDENTIAL(2);

  companion object {
    fun ofRaw(raw: Int): AuthRequirementWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The presence check bound to a created key, reported in a tier report. */
enum class AuthClassWire(val raw: Int) {
  NONE(0),
  BIOMETRIC_ONLY(1),
  BIOMETRIC_OR_DEVICE_CREDENTIAL(2),
  DEVICE_CREDENTIAL_ONLY(3);

  companion object {
    fun ofRaw(raw: Int): AuthClassWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Public-key wire format: uncompressed X9.63 point or DER SubjectPublicKeyInfo. */
enum class PublicKeyFormatWire(val raw: Int) {
  RAW_X962(0),
  SPKI(1);

  companion object {
    fun ofRaw(raw: Int): PublicKeyFormatWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Attestation wire format: a certificate chain or none. */
enum class AttestationFormatWire(val raw: Int) {
  ANDROID_KEY_CHAIN(0),
  NONE(1);

  companion object {
    fun ofRaw(raw: Int): AttestationFormatWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Signature wire encoding: X9.62 DER or fixed 64-byte r||s. */
enum class SignEncodingWire(val raw: Int) {
  DER(0),
  RAW_RS(1);

  companion object {
    fun ofRaw(raw: Int): SignEncodingWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A key-generation request. The achieved tier and auth class are read back from
 * the created key, never assumed from the request.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KeySpecWire (
  /** Stable, app-scoped name for the key. */
  val alias: String,
  /** Tier selection kind. */
  val tierPolicyKind: TierPolicyKindWire,
  /** Set only when [tierPolicyKind] is `atLeast`; null otherwise. */
  val atLeastClass: HardwareClassWire? = null,
  /** The presence check to bind to the key; `none` creates a silent key. */
  val authRequirement: AuthRequirementWire,
  /**
   * Auth reuse window in seconds; null and 0 both mean per-use. Baked into the
   * key where the platform supports it (Android); a sign-time value elsewhere.
   */
  val authValiditySeconds: Long? = null,
  /** Whether a biometric re-enrollment invalidates the key. */
  val invalidateOnBiometricEnrollment: Boolean,
  /** Bound into the key at generation; there is no call-time challenge. */
  val attestationChallenge: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KeySpecWire {
      val alias = pigeonVar_list[0] as String
      val tierPolicyKind = pigeonVar_list[1] as TierPolicyKindWire
      val atLeastClass = pigeonVar_list[2] as HardwareClassWire?
      val authRequirement = pigeonVar_list[3] as AuthRequirementWire
      val authValiditySeconds = pigeonVar_list[4] as Long?
      val invalidateOnBiometricEnrollment = pigeonVar_list[5] as Boolean
      val attestationChallenge = pigeonVar_list[6] as ByteArray?
      return KeySpecWire(alias, tierPolicyKind, atLeastClass, authRequirement, authValiditySeconds, invalidateOnBiometricEnrollment, attestationChallenge)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      alias,
      tierPolicyKind,
      atLeastClass,
      authRequirement,
      authValiditySeconds,
      invalidateOnBiometricEnrollment,
      attestationChallenge,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KeySpecWire
    return MessagesPigeonUtils.deepEquals(this.alias, other.alias) && MessagesPigeonUtils.deepEquals(this.tierPolicyKind, other.tierPolicyKind) && MessagesPigeonUtils.deepEquals(this.atLeastClass, other.atLeastClass) && MessagesPigeonUtils.deepEquals(this.authRequirement, other.authRequirement) && MessagesPigeonUtils.deepEquals(this.authValiditySeconds, other.authValiditySeconds) && MessagesPigeonUtils.deepEquals(this.invalidateOnBiometricEnrollment, other.invalidateOnBiometricEnrollment) && MessagesPigeonUtils.deepEquals(this.attestationChallenge, other.attestationChallenge)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.alias)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tierPolicyKind)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.atLeastClass)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.authRequirement)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.authValiditySeconds)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.invalidateOnBiometricEnrollment)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.attestationChallenge)
    return result
  }
  override fun toString(): String {
    return "KeySpecWire(alias=$alias, tierPolicyKind=$tierPolicyKind, atLeastClass=$atLeastClass, authRequirement=$authRequirement, authValiditySeconds=$authValiditySeconds, invalidateOnBiometricEnrollment=$invalidateOnBiometricEnrollment, attestationChallenge=${attestationChallenge?.contentToString()})"
  }
}

/**
 * One report shape for every operation that reads a key's tier. `requested` and
 * `authEnforced` are null on a re-read, where the policy is not stored with the
 * key and the platform may not read the created access control back.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SecurityTierReportWire (
  val achieved: SecurityLevelWire,
  val requestedKind: TierPolicyKindWire? = null,
  val requestedAtLeastClass: HardwareClassWire? = null,
  val meetsFloor: Boolean,
  val evidence: TierEvidenceWire,
  val authEnforced: AuthClassWire? = null,
  val invalidated: Boolean,
  val schemaVersion: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SecurityTierReportWire {
      val achieved = pigeonVar_list[0] as SecurityLevelWire
      val requestedKind = pigeonVar_list[1] as TierPolicyKindWire?
      val requestedAtLeastClass = pigeonVar_list[2] as HardwareClassWire?
      val meetsFloor = pigeonVar_list[3] as Boolean
      val evidence = pigeonVar_list[4] as TierEvidenceWire
      val authEnforced = pigeonVar_list[5] as AuthClassWire?
      val invalidated = pigeonVar_list[6] as Boolean
      val schemaVersion = pigeonVar_list[7] as Long
      return SecurityTierReportWire(achieved, requestedKind, requestedAtLeastClass, meetsFloor, evidence, authEnforced, invalidated, schemaVersion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      achieved,
      requestedKind,
      requestedAtLeastClass,
      meetsFloor,
      evidence,
      authEnforced,
      invalidated,
      schemaVersion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SecurityTierReportWire
    return MessagesPigeonUtils.deepEquals(this.achieved, other.achieved) && MessagesPigeonUtils.deepEquals(this.requestedKind, other.requestedKind) && MessagesPigeonUtils.deepEquals(this.requestedAtLeastClass, other.requestedAtLeastClass) && MessagesPigeonUtils.deepEquals(this.meetsFloor, other.meetsFloor) && MessagesPigeonUtils.deepEquals(this.evidence, other.evidence) && MessagesPigeonUtils.deepEquals(this.authEnforced, other.authEnforced) && MessagesPigeonUtils.deepEquals(this.invalidated, other.invalidated) && MessagesPigeonUtils.deepEquals(this.schemaVersion, other.schemaVersion)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.achieved)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.requestedKind)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.requestedAtLeastClass)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.meetsFloor)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.evidence)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.authEnforced)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.invalidated)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.schemaVersion)
    return result
  }
  override fun toString(): String {
    return "SecurityTierReportWire(achieved=$achieved, requestedKind=$requestedKind, requestedAtLeastClass=$requestedAtLeastClass, meetsFloor=$meetsFloor, evidence=$evidence, authEnforced=$authEnforced, invalidated=$invalidated, schemaVersion=$schemaVersion)"
  }
}

/**
 * Options for a signature.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SignOptionsWire (
  val encoding: SignEncodingWire
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SignOptionsWire {
      val encoding = pigeonVar_list[0] as SignEncodingWire
      return SignOptionsWire(encoding)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      encoding,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SignOptionsWire
    return MessagesPigeonUtils.deepEquals(this.encoding, other.encoding)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.encoding)
    return result
  }
  override fun toString(): String {
    return "SignOptionsWire(encoding=$encoding)"
  }
}

/**
 * The attestation for a key: a certificate chain (`androidKeyChain`), one
 * DER-encoded certificate per element, or `none` with a null chain. The library
 * produces attestation and never verifies it.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AttestationResultWire (
  val format: AttestationFormatWire,
  val chain: List<ByteArray?>? = null,
  val schemaVersion: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AttestationResultWire {
      val format = pigeonVar_list[0] as AttestationFormatWire
      val chain = pigeonVar_list[1] as List<ByteArray?>?
      val schemaVersion = pigeonVar_list[2] as Long
      return AttestationResultWire(format, chain, schemaVersion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      format,
      chain,
      schemaVersion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AttestationResultWire
    return MessagesPigeonUtils.deepEquals(this.format, other.format) && MessagesPigeonUtils.deepEquals(this.chain, other.chain) && MessagesPigeonUtils.deepEquals(this.schemaVersion, other.schemaVersion)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.format)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.chain)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.schemaVersion)
    return result
  }
  override fun toString(): String {
    return "AttestationResultWire(format=$format, chain=$chain, schemaVersion=$schemaVersion)"
  }
}

/**
 * The result of generating a key: an opaque handle id carrying no key material,
 * and the tier report read back from the created key.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class GenerateResultWire (
  val handleId: String,
  val report: SecurityTierReportWire
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GenerateResultWire {
      val handleId = pigeonVar_list[0] as String
      val report = pigeonVar_list[1] as SecurityTierReportWire
      return GenerateResultWire(handleId, report)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      handleId,
      report,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GenerateResultWire
    return MessagesPigeonUtils.deepEquals(this.handleId, other.handleId) && MessagesPigeonUtils.deepEquals(this.report, other.report)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.handleId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.report)
    return result
  }
  override fun toString(): String {
    return "GenerateResultWire(handleId=$handleId, report=$report)"
  }
}

/**
 * A public key in one of the pinned formats. There is no matching private-key
 * surface anywhere in the contract.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PublicKeyWire (
  val format: PublicKeyFormatWire,
  val bytes: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PublicKeyWire {
      val format = pigeonVar_list[0] as PublicKeyFormatWire
      val bytes = pigeonVar_list[1] as ByteArray
      return PublicKeyWire(format, bytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      format,
      bytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PublicKeyWire
    return MessagesPigeonUtils.deepEquals(this.format, other.format) && MessagesPigeonUtils.deepEquals(this.bytes, other.bytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.format)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bytes)
    return result
  }
  override fun toString(): String {
    return "PublicKeyWire(format=$format, bytes=${bytes.contentToString()})"
  }
}

/**
 * The prompt for an auth-gated sign, non-null on [SignetHostApi.sign] only for a
 * gated key. The native side presents it and authenticates the hardware key
 * directly; a Dart-shown prompt could not. [authRequirement] must match the
 * key's and selects the prompt's authenticators.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AuthPromptWire (
  val title: String,
  val subtitle: String? = null,
  /** The fallback button label on a biometric-only prompt. */
  val negativeButtonText: String,
  /** Selects the prompt's authenticators; matches the key's requirement. */
  val authRequirement: AuthRequirementWire
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuthPromptWire {
      val title = pigeonVar_list[0] as String
      val subtitle = pigeonVar_list[1] as String?
      val negativeButtonText = pigeonVar_list[2] as String
      val authRequirement = pigeonVar_list[3] as AuthRequirementWire
      return AuthPromptWire(title, subtitle, negativeButtonText, authRequirement)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      subtitle,
      negativeButtonText,
      authRequirement,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AuthPromptWire
    return MessagesPigeonUtils.deepEquals(this.title, other.title) && MessagesPigeonUtils.deepEquals(this.subtitle, other.subtitle) && MessagesPigeonUtils.deepEquals(this.negativeButtonText, other.negativeButtonText) && MessagesPigeonUtils.deepEquals(this.authRequirement, other.authRequirement)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.title)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.subtitle)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.negativeButtonText)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.authRequirement)
    return result
  }
  override fun toString(): String {
    return "AuthPromptWire(title=$title, subtitle=$subtitle, negativeButtonText=$negativeButtonText, authRequirement=$authRequirement)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SecurityLevelWire.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TierEvidenceWire.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TierPolicyKindWire.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          HardwareClassWire.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AuthRequirementWire.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AuthClassWire.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PublicKeyFormatWire.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AttestationFormatWire.ofRaw(it.toInt())
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SignEncodingWire.ofRaw(it.toInt())
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KeySpecWire.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SecurityTierReportWire.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SignOptionsWire.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AttestationResultWire.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GenerateResultWire.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PublicKeyWire.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AuthPromptWire.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SecurityLevelWire -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is TierEvidenceWire -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is TierPolicyKindWire -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is HardwareClassWire -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is AuthRequirementWire -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is AuthClassWire -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is PublicKeyFormatWire -> {
        stream.write(135)
        writeValue(stream, value.raw.toLong())
      }
      is AttestationFormatWire -> {
        stream.write(136)
        writeValue(stream, value.raw.toLong())
      }
      is SignEncodingWire -> {
        stream.write(137)
        writeValue(stream, value.raw.toLong())
      }
      is KeySpecWire -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is SecurityTierReportWire -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is SignOptionsWire -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is AttestationResultWire -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is GenerateResultWire -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is PublicKeyWire -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is AuthPromptWire -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * The calls Dart makes into the native core. Errors do not cross as data: the
 * core throws a platform error whose code is one of the closed error tokens in
 * `conformance/errors.json`, which the idiomatic layer maps to a typed
 * exception. The native side is not more trusted than Dart; both run in the
 * same process and the only trust anchors are the hardware and a remote
 * attestation verifier this library never calls.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface SignetHostApi {
  /**
   * Generates a non-exportable P-256 key. Fails `keyAlreadyExists` on an
   * existing alias, `unavailableTier` when a hard policy cannot be met.
   */
  fun generateKey(spec: KeySpecWire): GenerateResultWire
  /** Public key only; the private key has no export path. */
  fun getPublicKey(handleId: String, format: PublicKeyFormatWire): PublicKeyWire
  /**
   * Signs a 32-byte digest. A null [prompt] is the silent path and raises no
   * prompt; a non-null [prompt] drives an auth-gated sign whose biometric prompt
   * the native side presents and authenticates directly. A wrong-length digest
   * is rejected `invalidArgument` before any key access. A second concurrent
   * gated sign is rejected `authInProgress`; a gated key with no presentable host
   * UI raises `authContextRequired`.
   */
  fun sign(handleId: String, digest: ByteArray, options: SignOptionsWire, prompt: AuthPromptWire?, callback: (Result<ByteArray>) -> Unit)
  /** Attestation bound at generation; takes no call-time challenge. */
  fun getAttestation(handleId: String): AttestationResultWire
  /** Re-reads a key's tier; does not throw on an invalidated-but-present key. */
  fun getSecurityTier(handleId: String): SecurityTierReportWire
  /** Whether a key exists for the alias. */
  fun exists(alias: String): Boolean
  /** Deletes the key for the alias. Idempotent: a missing alias is not an error. */
  fun deleteKey(alias: String)

  companion object {
    /** The codec used by SignetHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `SignetHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SignetHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.signet.SignetHostApi.generateKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val specArg = args[0] as KeySpecWire
            val wrapped: List<Any?> = try {
              listOf(api.generateKey(specArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.signet.SignetHostApi.getPublicKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleIdArg = args[0] as String
            val formatArg = args[1] as PublicKeyFormatWire
            val wrapped: List<Any?> = try {
              listOf(api.getPublicKey(handleIdArg, formatArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.signet.SignetHostApi.sign$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleIdArg = args[0] as String
            val digestArg = args[1] as ByteArray
            val optionsArg = args[2] as SignOptionsWire
            val promptArg = args[3] as AuthPromptWire?
            api.sign(handleIdArg, digestArg, optionsArg, promptArg) { result: Result<ByteArray> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.signet.SignetHostApi.getAttestation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getAttestation(handleIdArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.signet.SignetHostApi.getSecurityTier$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getSecurityTier(handleIdArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.signet.SignetHostApi.exists$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val aliasArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.exists(aliasArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.signet.SignetHostApi.deleteKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val aliasArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.deleteKey(aliasArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
